### ISSUE TITLE
When adding many sprites to others, slow down.

### ISSUE THREAD

**Issue by vushu** [KTXSoftware/Kha2D#2]
Hello.
I tried adding 200 16x16 sprites to Scene.the.addOther(spr)

but my game slows down significantly, so now I use addEnemy and slow down is gone.
When am I supposed to use others?

**Comment by RobDangerous** [comment]
Please use the forum at http://forum.kode.tech for questions, this place is for bug reports.

**Comment by vushu** [comment]
Ah okay, I was not sure if this is a bug, I Will try the forum then.
